ci(workflow): 若内容未变更则跳过部署
之前的部署工作流即使在构建产物与目标分支内容完全相同的情况下也会创建一个新的提交。这导致了提交历史中充满了不必要的空更新。

本次变更修改了部署步骤，在提交前先使用 `git diff` 检查差异。如果未检测到任何变更，工作流将正常退出，从而避免了不必要的提交和推送。

diff --git a/.github/workflows/build-and-push.yml b/.github/workflows/build-and-push.yml
--- a/.github/workflows/build-and-push.yml
+++ b/.github/workflows/build-and-push.yml
@@ -38,11 +38,6 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-pnpm-
 
-      - name: Configure Git for Bot
-        run: |
-          git config user.name "github-actions[bot]"
-          git config user.email "github-actions[bot]@users.noreply.github.com"
-
       - name: Create remote ${{ env.TARGET_BRANCH }} branch
         run: |
           if ! git ls-remote --exit-code origin refs/heads/${{ env.TARGET_BRANCH }}; then
@@ -61,20 +56,34 @@ jobs:
       - name: Build project
         run: pnpm run build
 
-      - name: Deploy to ${{ env.TARGET_BRANCH }}
+
+      - name: Create temp repository
         run: |
           if [ ! -d "$ARTIFACT_DIR" ]; then
-              echo "Error: Build output directory ${{ env.ARTIFACT_DIR }} not found. Check build step."
-              exit 1
+            echo "Error: Build output directory ${{ env.ARTIFACT_DIR }} not found. Check build step."
+            exit 1
           fi
           cd ${{ env.ARTIFACT_DIR }}
           git init
+
+      - name: Configure Git for Bot
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+
+      - name: Deploy to ${{ env.TARGET_BRANCH }}
+        run: |
+
           git remote add origin ${{ env.REPO_URL }}
           git fetch origin ${{ env.TARGET_BRANCH }} --depth=1 || true
 
-
           git add -A .
-          git diff --quiet --cached FETCH_HEAD -- . && exit 0
+
+          if git diff --quiet --cached FETCH_HEAD -- . ; then
+            echo "Artifact content is identical to the content on ${{ env.TARGET_BRANCH }}. Skipping commit and push."
+            exit 0
+          fi
+
           git commit -m "${{ env.COMMIT_MESSAGE }}"
           git push origin +HEAD:${{ env.TARGET_BRANCH }}
 
